### ISSUE TITLE
Stop auto block PRs

### ISSUE THREAD

**Issue by liangyuanpeng** [kcl-lang/community#18]
## Enhancement

Now, the PR will auto block by github action bot and the reason is KCL using github action of CLA  to access and update information. 

I have tested on my fork repo : https://github.com/liangyuanpeng/kpm/pulls?q=is%3Apr+is%3Aclosed

The first PR is working for reproduce auto block PR. And then PR would not be auto block after i delete the github action CLA, 

For CLA, maybe you can try to https://github.com/cla-assistant/cla-assistant?tab=readme-ov-file#setup-your-own-instance-of-cla-assistant

@Peefy @zong-zhe

---

# Summary

Set `lock-pullrequest-aftermerge` to false for disable auto block PR, you can find it at `.github/workflows/cla.yaml`

```diff
-          lock-pullrequest-aftermerge: True
+          lock-pullrequest-aftermerge: false
```

**Comment by Peefy** [comment]
It works fine in this PR https://github.com/kcl-lang/modules/pull/123 Thank you! ❤️

**Comment by Nivedita-coder** [comment]
Hey @liangyuanpeng @Peefy,
Is this issue still open, if yes, I would like to work on it!! 🙌

**Comment by d4v1d03** [comment]
Hey @Peefy , sorry it's been time i lost track of this issue, have made the PRs for the open issues, for the kcl-openapi one, there was no need of changing as the "lock-pullrequest-aftermerge" was already set to false.

**Comment by liangyuanpeng** [comment]
@Nivedita-coder 
Sorry for the out of sync information, it's resolved.

@d4v1d03 
Thanks for your confirm that.
